--
-- PostgreSQL database dump
--

\restrict rlLFdUB7Q88dMYWKQOHCiGnSLNIrwVBDJdyZAW4c4brEMBdHif19IFLIRDAkhJv

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_categoria (
    id_categoria integer NOT NULL,
    nome_categoria character varying(30) NOT NULL,
    c_imagem character varying(100),
    dominio_id integer NOT NULL,
    status character varying(10) NOT NULL
);


ALTER TABLE public.catalog_categoria OWNER TO postgres;

--
-- Name: catalog_categoria_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_categoria ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_categoria_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_classificacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_classificacao (
    id bigint NOT NULL,
    subcategoria_id integer NOT NULL,
    termo_id integer NOT NULL
);


ALTER TABLE public.catalog_classificacao OWNER TO postgres;

--
-- Name: catalog_classificacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_classificacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_classificacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_dominio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_dominio (
    id_dominio integer NOT NULL,
    nome_dominio character varying(30) NOT NULL
);


ALTER TABLE public.catalog_dominio OWNER TO postgres;

--
-- Name: catalog_dominio_id_dominio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_dominio ALTER COLUMN id_dominio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_dominio_id_dominio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_pertence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_pertence (
    id bigint NOT NULL,
    dominio_id integer NOT NULL,
    termo_id integer NOT NULL
);


ALTER TABLE public.catalog_pertence OWNER TO postgres;

--
-- Name: catalog_pertence_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_pertence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_pertence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_profile (
    id bigint NOT NULL,
    role character varying(15) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.catalog_profile OWNER TO postgres;

--
-- Name: catalog_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_subcategoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_subcategoria (
    id_subcategoria integer NOT NULL,
    nome_subcategoria character varying(30) NOT NULL,
    categoria_id integer,
    status character varying(10) NOT NULL
);


ALTER TABLE public.catalog_subcategoria OWNER TO postgres;

--
-- Name: catalog_subcategoria_id_subcategoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_subcategoria ALTER COLUMN id_subcategoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_subcategoria_id_subcategoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_termo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_termo (
    id_termo integer NOT NULL,
    nome_termo character varying(30) NOT NULL,
    descricao text,
    t_imagem character varying(100),
    carrossel boolean NOT NULL,
    created_at timestamp with time zone,
    created_by_id integer,
    feedback text,
    status character varying(10) NOT NULL
);


ALTER TABLE public.catalog_termo OWNER TO postgres;

--
-- Name: catalog_termo_id_termo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_termo ALTER COLUMN id_termo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_termo_id_termo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_video; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_video (
    id_video integer NOT NULL,
    tipo_video character varying(20) NOT NULL,
    titulo character varying(30) NOT NULL,
    video character varying(100) NOT NULL,
    termo_id integer NOT NULL,
    convertido boolean NOT NULL,
    feedback text,
    status character varying(10) NOT NULL,
    uploaded_by_id integer
);


ALTER TABLE public.catalog_video OWNER TO postgres;

--
-- Name: catalog_video_id_video_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_video ALTER COLUMN id_video ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_video_id_video_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add dominio	7	add_dominio
26	Can change dominio	7	change_dominio
27	Can delete dominio	7	delete_dominio
28	Can view dominio	7	view_dominio
29	Can add termo	8	add_termo
30	Can change termo	8	change_termo
31	Can delete termo	8	delete_termo
32	Can view termo	8	view_termo
33	Can add categoria	9	add_categoria
34	Can change categoria	9	change_categoria
35	Can delete categoria	9	delete_categoria
36	Can view categoria	9	view_categoria
37	Can add subcategoria	10	add_subcategoria
38	Can change subcategoria	10	change_subcategoria
39	Can delete subcategoria	10	delete_subcategoria
40	Can view subcategoria	10	view_subcategoria
41	Can add video	11	add_video
42	Can change video	11	change_video
43	Can delete video	11	delete_video
44	Can view video	11	view_video
45	Can add pertence	12	add_pertence
46	Can change pertence	12	change_pertence
47	Can delete pertence	12	delete_pertence
48	Can view pertence	12	view_pertence
49	Can add classificacao	13	add_classificacao
50	Can change classificacao	13	change_classificacao
51	Can delete classificacao	13	delete_classificacao
52	Can view classificacao	13	view_classificacao
67	Can add profile	34	add_profile
68	Can change profile	34	change_profile
69	Can delete profile	34	delete_profile
70	Can view profile	34	view_profile
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$rGhVs1bDxM92A12DQHCzGQ$kDBwK0i6zj/hZas4cx6nyoHszb7hghVGR8UQzswCwgU=	\N	t	luis			pizzirano@gmail.com	t	t	2026-05-03 23:08:36.304679+00
2	pbkdf2_sha256$1000000$lbyiXAOZBldyOe8rMoeiBQ$R/hMCsxcBH25qv1z6Ra6eOZF7bMUKOMW3tfAWWbTqcE=	2026-05-03 23:18:57.347931+00	t	task			pizzirano@gmail.com	t	t	2026-05-03 23:18:45.461291+00
10	pbkdf2_sha256$1000000$k5pzbAE2mMq4JYgHJljtUg$ywmPkB2RxYvdouF7GW9/1WzH2H0J/EbocclU1OaGXDE=	2026-05-30 20:36:44.517259+00	f	edit_test_user				f	t	2026-05-30 20:32:42.087216+00
5	pbkdf2_sha256$1000000$alovu0Ga8RE51tvTWmSMLG$rpVCCgR97xZgHTbrWKBN5hko/K7RmuxTW2oSaV/2xpo=	2026-05-30 18:49:39.493911+00	t	test_admin_validation			admin@example.com	t	t	2026-05-30 18:48:31.27199+00
11	pbkdf2_sha256$1000000$exaRvv0h5Hh9wYoSqJrNJt$nwrwVob2p2JzucJ6qLqZWkujipKK/nDShw5zDgvBbEk=	2026-05-30 20:41:46.202963+00	t	mod_check_user				t	t	2026-05-30 20:41:02.627464+00
4	pbkdf2_sha256$1000000$1JtUxULQdeNNxXJeGZpHGv$mZo4kYVse/B4HVhxwiWHpCpsKNzya9sC0D1cQyGNn2k=	2026-05-30 19:17:35.154522+00	f	test_user_validation			testuser@example.com	f	t	2026-05-30 18:48:30.457009+00
7	pbkdf2_sha256$1000000$AJcI4NrGUlyhaWgA3zu7Cd$h8igtAnKytshbeAob3Yx3nIaCiz/PKKkqfKZgZfQJEc=	2026-05-30 19:49:53.592127+00	f	test_submitter				f	t	2026-05-30 19:49:34.256791+00
9	pbkdf2_sha256$1000000$ebj05cwvlgeaNZGk5rWcLV$46LJp4DjfxY3hXPDuLJvKcPFIuiqG30xZnaZZwkEquo=	2026-05-30 19:51:24.990952+00	f	mod_test				f	t	2026-05-30 19:51:24.225402+00
8	pbkdf2_sha256$1000000$AzuTDsow58dDvSdoFUchqL$+lzggihPkOpvQnB8fGr7lXakQh2BO9IzQUHtLTpGrUM=	2026-05-30 19:52:44.216875+00	f	orquestrador_test				f	t	2026-05-30 19:50:43.36559+00
3	pbkdf2_sha256$1000000$baJnApnDHhU9lHe5fFdLkP$d6yOXAkPDdVcNnxCxYZmqOCjLprm/G+fRPwDtYS/bHk=	2026-06-01 12:27:50.737709+00	f	luisFernando	Luis	Pizzirani	pizzirano@gmail.com	f	t	2026-05-29 20:03:16.484225+00
6	pbkdf2_sha256$1000000$oBt20umqvqKnqakqKeIAh9$cwUU6+nKWiE6o1rDcGo7BHWSfak7AwWuRmUeclB/0dg=	2026-06-01 12:29:26.783452+00	t	duser			pizzirano@gmail.com	t	t	2026-05-30 19:26:55.416648+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: catalog_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_categoria (id_categoria, nome_categoria, c_imagem, dominio_id, status) FROM stdin;
1	Gastronomia	categorias/food.webp	1	APPROVED
2	Turismo		1	APPROVED
3	Alimentação		1	APPROVED
4	CatTest		1	APPROVED
5	fgnsfdgn	categorias/Cronograma_de_entrega_tcc-banca.jpeg	1	APPROVED
6	Atrações turísticas	categorias/PG_48.png	1	APPROVED
7	nova categoria	categorias/jesus.jpg	1	PENDING
\.


--
-- Data for Name: catalog_classificacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_classificacao (id, subcategoria_id, termo_id) FROM stdin;
1	1	1
2	2	2
3	2	3
4	2	4
5	2	5
6	3	6
7	4	6
8	5	8
9	6	9
10	7	10
11	3	11
12	5	12
13	1	13
\.


--
-- Data for Name: catalog_dominio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_dominio (id_dominio, nome_dominio) FROM stdin;
1	Turismo
\.


--
-- Data for Name: catalog_pertence; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_pertence (id, dominio_id, termo_id) FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	1	5
6	1	6
7	1	8
8	1	9
9	1	10
10	1	11
11	1	12
12	1	13
\.


--
-- Data for Name: catalog_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_profile (id, role, user_id) FROM stdin;
11	MODERATOR	11
2	COMMON	1
3	COMMON	2
5	COMMON	5
4	COMMON	4
1	COMMON	3
6	COMMON	6
7	COMMON	7
9	MODERATOR	9
8	COMMON	8
10	COMMON	10
\.


--
-- Data for Name: catalog_subcategoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_subcategoria (id_subcategoria, nome_subcategoria, categoria_id, status) FROM stdin;
1	Restaurantes	1	APPROVED
2	Infraestrutura	2	APPROVED
3	Restaurantes	3	APPROVED
4	SubTest	4	APPROVED
5	bzdfgb	3	APPROVED
6	fff	5	APPROVED
7	Monumentos	6	APPROVED
\.


--
-- Data for Name: catalog_termo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_termo (id_termo, nome_termo, descricao, t_imagem, carrossel, created_at, created_by_id, feedback, status) FROM stdin;
3	VALIDATION TEST TERM NO VIDEO	Termo para validação sem vídeo		f	2026-05-30 18:48:59.845582+00	4	\N	APPROVED
5	VALIDATION TEST TERM IMAGE	Termo com imagem		f	2026-05-30 19:17:35.334649+00	4	\N	APPROVED
4	VALIDATION TEST TERM IMAGE	Termo com imagem		f	2026-05-30 19:15:42.987623+00	4	\N	APPROVED
2	VALIDATION TEST TERM	Termo para validação		f	2026-05-30 18:48:33.271145+00	4	\N	APPROVED
1	Teste	SInal em libras	termos/gato-feio.webp	t	2026-05-29 19:02:05.865144+00	\N	\N	APPROVED
7	Criado via ORM	desc		f	2026-05-30 19:50:44.228957+00	8	\N	REJECTED
12	Teste	"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"	termos/jesus_Eu2tlu7.jpg	t	2026-05-31 19:55:00.911681+00	3		APPROVED
6	Termo6 edited	edited desc	termos/food.webp	t	2026-05-30 19:23:29.744308+00	10	\N	APPROVED
8	Sinal Aeroporto	gnfgn	termos/food_HbDuM3E.webp	t	2026-05-30 20:48:39.763163+00	6	\N	APPROVED
9	turismo	fgnfg	termos/Cronograma_de_entrega_tcc-banca.jpeg	t	2026-05-30 21:07:24.003124+00	3		APPROVED
10	Teste usuario	"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"	termos/PG_55.png	t	2026-05-31 18:58:02.743963+00	3		AJUSTE
11	Teste usuario	"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"		t	2026-05-31 19:44:27.75149+00	3		APPROVED
13	Teste	fglahkbfhkswbfk	termos/mermaid-diagram.png	t	2026-06-01 12:28:43.80614+00	3		APPROVED
\.


--
-- Data for Name: catalog_video; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_video (id_video, tipo_video, titulo, video, termo_id, convertido, feedback, status, uploaded_by_id) FROM stdin;
2	Sinal	Restaurante alimentação	videos/Sinal_Almoço.MOV	6	f	\N	APPROVED	3
1	Sinal	teste	videos/CrudBoot.mp4	1	f	\N	APPROVED	\N
4	Sinal	ORM2	videos/orm2.mp4	7	f	\N	REJECTED	8
3	Sinal	ORM1	videos/orm1.mp4	7	f	\N	REJECTED	8
5	Sinal	Ônibus	videos/Sinal_Almoço_SESDIpL.MOV	8	f	\N	APPROVED	6
6	Sinal	teste	videos/Sinal_Almoço_aWZmYlY.MOV	9	f	\N	APPROVED	3
7	Sinal	teste usuario	videos/Camboriú.MOV	10	f	\N	AJUSTE	3
8	Sinal	jesus	videos/Camboriú_wMPuFJh.MOV	11	f	\N	APPROVED	3
9	Sinal	jesus	videos/Camboriú_JiHpXLi.MOV	12	f	\N	APPROVED	3
10	Sinal	teste01/06	videos/Camboriú_4L8gjxY.MOV	13	f	\N	APPROVED	3
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-03 23:19:13.499234+00	1	Turismo	1	[{"added": {}}]	7	2
2	2026-05-03 23:21:03.22182+00	1	Gastronomia	1	[{"added": {}}]	9	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	catalog	dominio
8	catalog	termo
9	catalog	categoria
10	catalog	subcategoria
11	catalog	video
12	catalog	pertence
13	catalog	classificacao
34	catalog	profile
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-03 22:48:09.267481+00
2	auth	0001_initial	2026-05-03 22:48:09.631719+00
3	admin	0001_initial	2026-05-03 22:48:09.757109+00
4	admin	0002_logentry_remove_auto_add	2026-05-03 22:48:09.788016+00
5	admin	0003_logentry_add_action_flag_choices	2026-05-03 22:48:09.805893+00
6	contenttypes	0002_remove_content_type_name	2026-05-03 22:48:09.849044+00
7	auth	0002_alter_permission_name_max_length	2026-05-03 22:48:09.867417+00
8	auth	0003_alter_user_email_max_length	2026-05-03 22:48:09.883508+00
9	auth	0004_alter_user_username_opts	2026-05-03 22:48:09.904841+00
10	auth	0005_alter_user_last_login_null	2026-05-03 22:48:09.923199+00
11	auth	0006_require_contenttypes_0002	2026-05-03 22:48:09.927643+00
12	auth	0007_alter_validators_add_error_messages	2026-05-03 22:48:09.949815+00
13	auth	0008_alter_user_username_max_length	2026-05-03 22:48:10.005574+00
14	auth	0009_alter_user_last_name_max_length	2026-05-03 22:48:10.027709+00
15	auth	0010_alter_group_name_max_length	2026-05-03 22:48:10.051689+00
16	auth	0011_update_proxy_permissions	2026-05-03 22:48:10.066982+00
17	auth	0012_alter_user_first_name_max_length	2026-05-03 22:48:10.081671+00
18	catalog	0001_initial	2026-05-03 22:48:10.501425+00
19	sessions	0001_initial	2026-05-03 22:48:10.575146+00
34	catalog	0002_termo_created_at_termo_created_by_termo_feedback_and_more	2026-05-29 19:02:06.990679+00
35	catalog	0003_categoria_status_subcategoria_status	2026-05-31 19:31:03.101206+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
4bshix0m88ck0zwjhsi2p9mft9oxiuif	.eJxVjMsOwiAQRf-FtSHA8KpL934DGRiQqoGktCvjv2uTLnR7zzn3xQJuaw3byEuYiZ2ZYqffLWJ65LYDumO7dZ56W5c58l3hBx382ik_L4f7d1Bx1G8NoKdopfPOTEkKKFBkAQUKEQoRemtSdokERnDWCg3CZGmK9pFQYGLvD8o3N78:1wJg5R:lpKoXQlW6F5_o3WKx6tzAq-YHt2pXHNeFey57F2vLko	2026-05-17 23:18:57.389705+00
wg2jz1j87tg59dzxpoprpihky35yizxf	.eJxVjDsOwjAQBe_iGln-rR1T0nMGa9cfHEC2FCcV4u4QKQW0b2beiwXc1hq2kZcwJ3ZmUrDT70gYH7ntJN2x3TqPva3LTHxX-EEHv_aUn5fD_TuoOOq31nIiW5QELCprICqYQQoBKpI0MVnvUaOZjC5AmqIx3pEDZYlAOQvs_QEHNTfD:1wTQNY:i1Z3BBG_LT92A8uv3RIsgR2Hl2LGgs6pcVmfkGjJ8yw	2026-06-13 20:33:56.529901+00
wqsyxkh79dhovcxp2w4us8285n0gt4yq	.eJxVjMEOwiAQRP-FsyG2wLZ49O43kGV3kaqBpLQn47_bJj3obTLvzbxVwHXJYW0yh4nVRVl1-u0i0lPKDviB5V411bLMU9S7og_a9K2yvK6H-3eQseVtjZAiC3nnKAJ7C8myN72hIXVbpGRcHAyL9AB-hCSGRyOYzjYKSGfV5wsXWTkS:1wTOjY:M0bwPTqSErImdY2K262R91Icb6oC-XlSe_EpFtC2TQc	2026-06-13 18:48:32.979099+00
8mlq687sxw9ntm8juz1gyiogbxe11gc0	.eJxVjEEOwiAQRe_C2pCBAAWX7j0DGWZAqgaS0q6Md9cmXej2v_f-S0Tc1hq3kZc4szgLBeL0OyakR2474Tu2W5fU27rMSe6KPOiQ1875eTncv4OKo35r53zxiMVayyERKQhkCtoEha3zxoAJRRujOFjQRSk9sfaZ0E0QwKF4fwAIrTem:1wTQO0:bdVde5d2GpgEPVnzg34H51KCLlB_g5WRXYz6ISl6PhY	2026-06-13 20:34:24.324305+00
qoimzpvxw6ukmw7697mzxd5kadw5fvy7	.eJxVjEEOwiAQRe_C2pABoQwu3XsGMjBUqgaS0q6Md7dNutDtf-_9twi0LiWsPc9hYnERCsTpd4yUnrnuhB9U702mVpd5inJX5EG7vDXOr-vh_h0U6mWrR8wjeJW90dFSQqc9K2Mog9WWNaBxDBY1k4t62DR1dmZQ1nNCRIji8wXzgDch:1wTQQG:dmGULI4JbVHrfnTipe3HKSlEPgEWksq1dIQn2Nov0go	2026-06-13 20:36:44.54737+00
dyovl3nq3earo21unc83ngdqxuub589v	.eJxVjEsOwiAUAO_C2hA-hVdcuu8ZCO8BUjWQlHZlvLsh6UK3M5N5Mx-Ovfijp82vkV2ZYZdfhoGeqQ4RH6HeG6dW921FPhJ-2s6XFtPrdrZ_gxJ6GdsYhIOETpBCMs4oC9NETkWVBWkNUmEiIyhnCACUE9pZzMZKjVJbYJ8v5UM3qA:1wTOk0:zbGwYahRni0fSli2KaZg5LgsL0qFdl1AqehQaJDDNtg	2026-06-13 18:49:00.871878+00
ytjv2nf5h3camvv8vm9iuuieg015vmt1	.eJxVjDsOwyAQBe9CHSEwy8cp0_sMiGVXwUkEkrGrKHePkFwk7ZuZ9xYxHXuJR-ctriSuQmtx-R0x5SfXQeiR6r3J3Oq-rSiHIk_a5dKIX7fT_TsoqZdRI7C3aHzwbpqRCSYMsw_gLHlI2XAmgw6ASAViSOgQtFZZG8pWK_H5Ag1rOC4:1wTQUR:gdAzWbXBurFxFKPQJ0SVs4Lj-PXv9jdInwPo-fE5yfY	2026-06-13 20:41:03.631408+00
0yt1doscszax7hmr67t3x6lxdrup3qhv	.eJxVjEsOwiAUAO_C2hA-hVdcuu8ZCO8BUjWQlHZlvLsh6UK3M5N5Mx-Ovfijp82vkV2ZYZdfhoGeqQ4RH6HeG6dW921FPhJ-2s6XFtPrdrZ_gxJ6GdsYhIOETpBCMs4oC9NETkWVBWkNUmEiIyhnCACUE9pZzMZKjVJbYJ8v5UM3qA:1wTOkd:1pQ7F9KsliuVokZ15eVGNIjI_4_90UdvQfg97y9WMLA	2026-06-13 18:49:39.504115+00
i06vrgu0owk7a4f5vs7tasjfz90ufenf	.eJxVjDsOwyAQBe9CHSEwy8cp0_sMiGVXwUkEkrGrKHePkFwk7ZuZ9xYxHXuJR-ctriSuQmtx-R0x5SfXQeiR6r3J3Oq-rSiHIk_a5dKIX7fT_TsoqZdRI7C3aHzwbpqRCSYMsw_gLHlI2XAmgw6ASAViSOgQtFZZG8pWK_H5Ag1rOC4:1wTQV8:nxw2IgYRFauQVCeG8hL8NJjBUoC9m_T2m4q9Dl7ViB0	2026-06-13 20:41:46.248928+00
sms9zdvdmfc72at50h0g8gck4eqhzvg7	.eJxVjEEOwiAQRe_C2hCmDKW4dO8ZCAODVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIsUJx-NwrxwXUH6R7qrcnY6rrMJHdFHrTLa0v8vBzu30EJvXzrSVHObAGdVhMbiHHArBxrAhg5EoFG5UApTIMlHR3kEcBoctbYYFG8P9WzNwQ:1wTOzm:0fFlIhmLDK0o85O35VaFaBYJ2nkMkxMI1FLkiqZot6E	2026-06-13 19:05:18.057081+00
67qbi0iym38ke6iuki4yumnztozdzjr1	.eJxVjEEOwiAQRe_C2hCmDKW4dO8ZCAODVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIsUJx-NwrxwXUH6R7qrcnY6rrMJHdFHrTLa0v8vBzu30EJvXzrSVHObAGdVhMbiHHArBxrAhg5EoFG5UApTIMlHR3kEcBoctbYYFG8P9WzNwQ:1wTP03:w0dQ0VPjAK1Y1ejT9jiZMIt-or4M95fmzfnAroCL-uY	2026-06-13 19:05:35.280308+00
9h6ois962w2rdc121yex1ummibo4ooxb	.eJxVjEEOwiAQRe_C2hCmDKW4dO8ZCAODVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIsUJx-NwrxwXUH6R7qrcnY6rrMJHdFHrTLa0v8vBzu30EJvXzrSVHObAGdVhMbiHHArBxrAhg5EoFG5UApTIMlHR3kEcBoctbYYFG8P9WzNwQ:1wTP9q:ET0oeuHQUOU3T8vsIsucuKHXEgwaBq2bKldjwESZCUE	2026-06-13 19:15:42.771572+00
597p4qkc2gmq4bo7ecles1rb912m3d4o	.eJxVjEEOwiAQRe_C2hCmDKW4dO8ZCAODVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIsUJx-NwrxwXUH6R7qrcnY6rrMJHdFHrTLa0v8vBzu30EJvXzrSVHObAGdVhMbiHHArBxrAhg5EoFG5UApTIMlHR3kEcBoctbYYFG8P9WzNwQ:1wTPBf:VKBrQvb6hfMWt3oeNQJazvp9oPU-FTMUCFZBl8e0NUM	2026-06-13 19:17:35.211375+00
z01qe10tgnwyljfu5tymut97jv0g42ql	.eJxVjMsOwiAQRf-FtSHQ4enSvd9AgGGkaiAp7cr479qkC93ec859sRC3tYZtlCXMyM7MstPvlmJ-lLYDvMd26zz3ti5z4rvCDzr4tWN5Xg7376DGUb-1BJvQ28lpQzJlLRwpomhBS2cEKY3FA6osrFUIjib0TvtMOgswMgJ7fwDUYzdh:1wTPge:eQR93hmUZgXLH1vcdRUAiTIJLyHcYJHvtcI28nLeEnU	2026-06-13 19:49:36.068935+00
ynuol4bhibfwohzgjvls7cl2gceg7mdz	.eJxVjMsOwiAQRf-FtSHQ4enSvd9AgGGkaiAp7cr479qkC93ec859sRC3tYZtlCXMyM7MstPvlmJ-lLYDvMd26zz3ti5z4rvCDzr4tWN5Xg7376DGUb-1BJvQ28lpQzJlLRwpomhBS2cEKY3FA6osrFUIjib0TvtMOgswMgJ7fwDUYzdh:1wTPgv:FpAPXI9k6sBk3XudWNXDyCagwm5iPiwjZ1pZHCgjbGg	2026-06-13 19:49:53.637387+00
j601a4r6rwckfvg2wl5ii7mlmyoiwzym	.eJxVjDsOwjAQBe_iGln-xD9Kes5grb1rHEC2FCcV4u4QKQW0b2bei0XY1hq3QUuckZ1ZYKffLUF-UNsB3qHdOs-9rcuc-K7wgw5-7UjPy-H-HVQY9Vvn4ETWFkuRCgQ6FxADaa1NBuOM196KyRBKkewEyttcipIkAoAJ3iv2_gDjYzeH:1wTPiO:8MNHKwNNLvPK1zs-G5mXMhnVAQao1FZLunEbEz8TeOo	2026-06-13 19:51:24.997048+00
ss951jem07li1rkms54r7oqpsw8bxth5	.eJxVjEEOwiAURO_C2hAKHwou3fcM5AMfqRpISrsy3t026UKXM-_NvJnHbS1-67T4ObErs-zy2wWMT6oHSA-s98Zjq-syB34o_KSdTy3R63a6fwcFe9nXYCAMBh1IFNEZQyYmm20ENCIPSqmwR5KYdQQ1Bp0cCu0oKxhJS0D2-QLnFDgP:1wTPj2:hTGGYztjmMzPhmhzmeSCMZbuf3Hs4xihXISrkecH9jA	2026-06-13 19:52:04.363139+00
hs5nwhee80st6rzvxu1ghy1wkw8vfbyj	.eJxVjEEOwiAURO_C2hAKHwou3fcM5AMfqRpISrsy3t026UKXM-_NvJnHbS1-67T4ObErs-zy2wWMT6oHSA-s98Zjq-syB34o_KSdTy3R63a6fwcFe9nXYCAMBh1IFNEZQyYmm20ENCIPSqmwR5KYdQQ1Bp0cCu0oKxhJS0D2-QLnFDgP:1wTPjI:LJU2HxkoD_troyAD1yZmYlVNSAe-BircW-qEqoaHJyU	2026-06-13 19:52:20.362446+00
rmb5kqmwg9wuj3bhf3j8gunrcgpbqn18	.eJxVjEEOwiAURO_C2hAKHwou3fcM5AMfqRpISrsy3t026UKXM-_NvJnHbS1-67T4ObErs-zy2wWMT6oHSA-s98Zjq-syB34o_KSdTy3R63a6fwcFe9nXYCAMBh1IFNEZQyYmm20ENCIPSqmwR5KYdQQ1Bp0cCu0oKxhJS0D2-QLnFDgP:1wTPjg:3L_djipXzZ_MvkKgVb8WtNNny2rHZrsAnD9Znv3nkuM	2026-06-13 19:52:44.287285+00
1lvr7ysmq5gaig07nokzmf6l9akx3k4n	.eJxVjDsOwjAQRO_iGllx1rExJT1niNb7wQHkSPlUiLuTSCmgnHlv5m16XJfSr7NM_cDmYlxjTr9lRnpK3Qk_sN5HS2NdpiHbXbEHne1tZHldD_fvoOBctjU0SUAoYqcaA3XxHJxPuUMVbYNgZgAHST0QOGKSLQTNKt4xSkvm8wUdUDkn:1wTQMM:PlNsQ_qSy1GtUP9g08AlofhaqDEvYHfVBcLH3_8xuBY	2026-06-13 20:32:42.988134+00
q6zhz4h8qkfjk6tpszlom4h7m3nrwapl	.eJxVjMsOwiAQRf-FtSHlIUxduvcbyMAMUjWQlHZl_HfbpAvd3nPOfYuA61LC2nkOE4mLcOL0u0VMT647oAfWe5Op1WWeotwVedAub434dT3cv4OCvWw15GgSZHNWAxqtHYFNZD1GzxBHMyqwxLRhi4PKyGAzkErgnPZeexSfL-W_N7I:1wU1lm:sb1V7o3DP8xp-RglJO85rAaEA1dKNsXHowNZEVBRJvs	2026-06-15 12:29:26.821386+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 70, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 11, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: catalog_categoria_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_categoria_id_categoria_seq', 7, true);


--
-- Name: catalog_classificacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_classificacao_id_seq', 13, true);


--
-- Name: catalog_dominio_id_dominio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_dominio_id_dominio_seq', 1, true);


--
-- Name: catalog_pertence_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_pertence_id_seq', 12, true);


--
-- Name: catalog_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_profile_id_seq', 11, true);


--
-- Name: catalog_subcategoria_id_subcategoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_subcategoria_id_subcategoria_seq', 7, true);


--
-- Name: catalog_termo_id_termo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_termo_id_termo_seq', 13, true);


--
-- Name: catalog_video_id_video_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_video_id_video_seq', 10, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 2, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 34, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 35, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: catalog_categoria catalog_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_categoria
    ADD CONSTRAINT catalog_categoria_pkey PRIMARY KEY (id_categoria);


--
-- Name: catalog_classificacao catalog_classificacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_classificacao
    ADD CONSTRAINT catalog_classificacao_pkey PRIMARY KEY (id);


--
-- Name: catalog_dominio catalog_dominio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_dominio
    ADD CONSTRAINT catalog_dominio_pkey PRIMARY KEY (id_dominio);


--
-- Name: catalog_pertence catalog_pertence_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_pertence
    ADD CONSTRAINT catalog_pertence_pkey PRIMARY KEY (id);


--
-- Name: catalog_profile catalog_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_profile
    ADD CONSTRAINT catalog_profile_pkey PRIMARY KEY (id);


--
-- Name: catalog_profile catalog_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_profile
    ADD CONSTRAINT catalog_profile_user_id_key UNIQUE (user_id);


--
-- Name: catalog_subcategoria catalog_subcategoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_subcategoria
    ADD CONSTRAINT catalog_subcategoria_pkey PRIMARY KEY (id_subcategoria);


--
-- Name: catalog_termo catalog_termo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_termo
    ADD CONSTRAINT catalog_termo_pkey PRIMARY KEY (id_termo);


--
-- Name: catalog_video catalog_video_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_video
    ADD CONSTRAINT catalog_video_pkey PRIMARY KEY (id_video);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: catalog_classificacao unique_classificacao; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_classificacao
    ADD CONSTRAINT unique_classificacao UNIQUE (termo_id, subcategoria_id);


--
-- Name: catalog_pertence unique_pertence; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_pertence
    ADD CONSTRAINT unique_pertence UNIQUE (termo_id, dominio_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: catalog_categoria_dominio_id_baddf520; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_categoria_dominio_id_baddf520 ON public.catalog_categoria USING btree (dominio_id);


--
-- Name: catalog_categoria_status_14686d8a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_categoria_status_14686d8a ON public.catalog_categoria USING btree (status);


--
-- Name: catalog_categoria_status_14686d8a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_categoria_status_14686d8a_like ON public.catalog_categoria USING btree (status varchar_pattern_ops);


--
-- Name: catalog_classificacao_subcategoria_id_7d2390e7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_classificacao_subcategoria_id_7d2390e7 ON public.catalog_classificacao USING btree (subcategoria_id);


--
-- Name: catalog_classificacao_termo_id_eb1369c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_classificacao_termo_id_eb1369c2 ON public.catalog_classificacao USING btree (termo_id);


--
-- Name: catalog_pertence_dominio_id_5f9d0e11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_pertence_dominio_id_5f9d0e11 ON public.catalog_pertence USING btree (dominio_id);


--
-- Name: catalog_pertence_termo_id_5e55593e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_pertence_termo_id_5e55593e ON public.catalog_pertence USING btree (termo_id);


--
-- Name: catalog_subcategoria_categoria_id_ecfbeffd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_subcategoria_categoria_id_ecfbeffd ON public.catalog_subcategoria USING btree (categoria_id);


--
-- Name: catalog_subcategoria_status_37f62fd8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_subcategoria_status_37f62fd8 ON public.catalog_subcategoria USING btree (status);


--
-- Name: catalog_subcategoria_status_37f62fd8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_subcategoria_status_37f62fd8_like ON public.catalog_subcategoria USING btree (status varchar_pattern_ops);


--
-- Name: catalog_termo_created_by_id_cd753fa5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_termo_created_by_id_cd753fa5 ON public.catalog_termo USING btree (created_by_id);


--
-- Name: catalog_termo_status_ee654b33; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_termo_status_ee654b33 ON public.catalog_termo USING btree (status);


--
-- Name: catalog_termo_status_ee654b33_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_termo_status_ee654b33_like ON public.catalog_termo USING btree (status varchar_pattern_ops);


--
-- Name: catalog_video_status_680a92be; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_video_status_680a92be ON public.catalog_video USING btree (status);


--
-- Name: catalog_video_status_680a92be_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_video_status_680a92be_like ON public.catalog_video USING btree (status varchar_pattern_ops);


--
-- Name: catalog_video_termo_id_ec4bc90a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_video_termo_id_ec4bc90a ON public.catalog_video USING btree (termo_id);


--
-- Name: catalog_video_uploaded_by_id_74738727; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_video_uploaded_by_id_74738727 ON public.catalog_video USING btree (uploaded_by_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_categoria catalog_categoria_dominio_id_baddf520_fk_catalog_d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_categoria
    ADD CONSTRAINT catalog_categoria_dominio_id_baddf520_fk_catalog_d FOREIGN KEY (dominio_id) REFERENCES public.catalog_dominio(id_dominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_classificacao catalog_classificaca_subcategoria_id_7d2390e7_fk_catalog_s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_classificacao
    ADD CONSTRAINT catalog_classificaca_subcategoria_id_7d2390e7_fk_catalog_s FOREIGN KEY (subcategoria_id) REFERENCES public.catalog_subcategoria(id_subcategoria) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_classificacao catalog_classificaca_termo_id_eb1369c2_fk_catalog_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_classificacao
    ADD CONSTRAINT catalog_classificaca_termo_id_eb1369c2_fk_catalog_t FOREIGN KEY (termo_id) REFERENCES public.catalog_termo(id_termo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_pertence catalog_pertence_dominio_id_5f9d0e11_fk_catalog_d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_pertence
    ADD CONSTRAINT catalog_pertence_dominio_id_5f9d0e11_fk_catalog_d FOREIGN KEY (dominio_id) REFERENCES public.catalog_dominio(id_dominio) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_pertence catalog_pertence_termo_id_5e55593e_fk_catalog_termo_id_termo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_pertence
    ADD CONSTRAINT catalog_pertence_termo_id_5e55593e_fk_catalog_termo_id_termo FOREIGN KEY (termo_id) REFERENCES public.catalog_termo(id_termo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_profile catalog_profile_user_id_7c4daf2b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_profile
    ADD CONSTRAINT catalog_profile_user_id_7c4daf2b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_subcategoria catalog_subcategoria_categoria_id_ecfbeffd_fk_catalog_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_subcategoria
    ADD CONSTRAINT catalog_subcategoria_categoria_id_ecfbeffd_fk_catalog_c FOREIGN KEY (categoria_id) REFERENCES public.catalog_categoria(id_categoria) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_termo catalog_termo_created_by_id_cd753fa5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_termo
    ADD CONSTRAINT catalog_termo_created_by_id_cd753fa5_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_video catalog_video_termo_id_ec4bc90a_fk_catalog_termo_id_termo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_video
    ADD CONSTRAINT catalog_video_termo_id_ec4bc90a_fk_catalog_termo_id_termo FOREIGN KEY (termo_id) REFERENCES public.catalog_termo(id_termo) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_video catalog_video_uploaded_by_id_74738727_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_video
    ADD CONSTRAINT catalog_video_uploaded_by_id_74738727_fk_auth_user_id FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict rlLFdUB7Q88dMYWKQOHCiGnSLNIrwVBDJdyZAW4c4brEMBdHif19IFLIRDAkhJv

