# Generated by Django 5.2.1 on 2025-05-30 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='catalog.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Sinal', 'Sinal'), ('Soletrando', 'Termo em Libras Soletrando'), ('Significado', 'Significado')], max_length=20)),
                ('titulo', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.termo')),
            ],
        ),
        migrations.CreateModel(
            name='Pertence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertencimentos', to='catalog.dominio')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertencimentos', to='catalog.termo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('termo', 'dominio'), name='unique_pertence')],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='catalog.subcategoria')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='catalog.termo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('termo', 'subcategoria'), name='unique_classificacao')],
            },
        ),
    ]
