# Generated by Django 5.2.1 on 2025-06-06 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id_dominio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_dominio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id_termo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_termo', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('t_imagem', models.ImageField(blank=True, null=True, upload_to='termos/')),
                ('carrossel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=30)),
                ('c_imagem', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='catalog.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_subcategoria', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_video', models.CharField(choices=[('Sinal', 'Sinal'), ('Soletrando', 'Termo em Libras Soletrando'), ('Significado', 'Significado')], max_length=20)),
                ('titulo', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='videos/')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.termo')),
            ],
        ),
        migrations.CreateModel(
            name='Pertence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertencimentos', to='catalog.dominio')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertencimentos', to='catalog.termo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('termo', 'dominio'), name='unique_pertence')],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='catalog.subcategoria')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='catalog.termo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('termo', 'subcategoria'), name='unique_classificacao')],
            },
        ),
    ]
