# Generated by Django 5.2.1 on 2025-05-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='dominio',
            old_name='nome',
            new_name='nome_dominio',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='nome',
            new_name='nome_subcategoria',
        ),
        migrations.RenameField(
            model_name='termo',
            old_name='nome',
            new_name='nome_termo',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='tipo',
            new_name='tipo_video',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dominio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='termo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dominio',
            name='id_dominio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='id_subcategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='termo',
            name='id_termo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='video',
            name='id_video',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
