# Generated by Django 5.2.3 on 2026-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_termo_created_at_termo_created_by_termo_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('AJUSTE', 'Ajuste Solicitado')], db_index=True, default='APPROVED', max_length=10),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('AJUSTE', 'Ajuste Solicitado')], db_index=True, default='APPROVED', max_length=10),
        ),
    ]
