# Generated by Django 5.2.3 on 2026-06-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categoria_status_subcategoria_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tipo_video',
            field=models.CharField(choices=[('Sinal', 'Sinal'), ('Datilologia', 'Datilologia'), ('Significado', 'Significado')], max_length=20),
        ),
    ]
